### ISSUE TITLE
Support Angular 12

### ISSUE THREAD

**Issue by dfederm** [BaherWael/ng-validate-equal#1]
When installing, I see:

> Package "ng-validate-equal" has an incompatible peer dependency to "@angular/common" (requires "^9.0.7" (extended), would install "12.0.0").

The package should be upgraded to support newer versions of Angular.

**Comment by baher-zakhary** [comment]
Hey David (@dfederm ),
Thank you for pointing out this issue for me.

I have released multiple versions of my package supporting Angular version 9, 10, 11 and 12

Please install the latest version of my package for Angular 12 support.

Best Regards,
Baher Zakhary
